#!/usr/bin/env bash

# This script displays numbers from 1 to 100 with FizzBuzz rules

# Using a for loop to iterate through numbers from 1 to 100
for ((num=1; num<=100; num++))
do
    # Check if the number is a multiple of both 3 and 5 (FizzBuzz)
    if ((num % 3 == 0)) && ((num % 5 == 0)); then
        echo "FizzBuzz"
    # Check if the number is a multiple of 3 (Fizz)
    elif ((num % 3 == 0)); then
        echo "Fizz"
    # Check if the number is a multiple of 5 (Buzz)
    elif ((num % 5 == 0)); then
        echo "Buzz"
    # Display the number if none of the above conditions are met
    else
        echo $num
    fi
done
