#!/usr/bin/env bash
# This script is didplaying "Best School" 10 time and "Hi" on the 9th iteration.
count=0
while [ $count -lt 10 ]
do 
	if [ $count -eq 9 ]; then
		echo "Hi"
	fi

	echo "Best School"
	((count++))
done
