#!/usr/bin/env bash

# This script displays different messages for specific loop iterations

# Initialize a counter variable. I've set the count to 1 because i want the loop to run 10 time. if it was set to 0, it would run 11 times
count=1

# Using a while loop to repeat the text 10 times (from 1 to 10)
while [ $count -le 10 ]
do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((count++))
done
