#!/usr/bin/env bash
# Script that configures an Ubuntu server with the following requirements:
# - Modify localhost to resolve to 127.0.0.2
# - Add an entry for facebook.com to resolve to 8.8.8.8

# Make a copy of the original hosts file
cp /etc/hosts ~/hosts.new

# Replace the IP address 127.0.0.1 with 127.0.0.2 in the copy of the hosts file
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

# Add a new entry for facebook.com with the IP address 8.8.8.8 to the copy of the hosts file
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new

# Overwrite the original hosts file with the updated one
cp -f ~/hosts.new /etc/hosts

